
import type { GlossaryTerm, ReadingText } from './types';

export const glossaryData: GlossaryTerm[] = [
  { id: 1, term: 'Abrasion', translation: 'Абразия', transcription: '/əˈbreɪʒən/', example: 'The rocks were smooth due to abrasion by the river.' },
  { id: 2, term: 'Alluvium', translation: 'Аллювий', transcription: '/əˈluːviəm/', example: 'The fertile plain is composed of rich alluvium.' },
  { id: 3, term: 'Aquifer', translation: 'Водоносный горизонт', transcription: '/ˈækwɪfər/', example: 'The town gets its water from a deep aquifer.' },
  { id: 4, term: 'Basalt', translation: 'Базальт', transcription: '/ˈbæsɔːlt/', example: 'Basalt is a common extrusive igneous rock.' },
  { id: 5, term: 'Bedrock', translation: 'Коренная порода', transcription: '/ˈbɛdrɒk/', example: 'The soil is thin, with bedrock close to the surface.' },
  { id: 6, term: 'Caldera', translation: 'Кальдера', transcription: '/kælˈdɛərə/', example: 'A large caldera formed after the volcano\'s massive eruption.' },
  { id: 7, term: 'Carbonate', translation: 'Карбонат', transcription: '/ˈkɑːrbənət/', example: 'Limestone is a type of carbonate sedimentary rock.' },
  { id: 8, term: 'Cleavage', translation: 'Спайность', transcription: '/ˈkliːvɪdʒ/', example: 'Mica exhibits perfect basal cleavage, splitting into thin sheets.' },
  { id: 9, term: 'Concretion', translation: 'Конкреция', transcription: '/kənˈkriːʃən/', example: 'They found a fossil inside a hard sandstone concretion.' },
  { id: 10, term: 'Continental Drift', translation: 'Дрейф континентов', transcription: '/ˌkɒntɪˈnɛntəl drɪft/', example: 'Alfred Wegener proposed the theory of continental drift.' },
  { id: 11, term: 'Core', translation: 'Ядро (Земли)', transcription: '/kɔːr/', example: 'The Earth\'s core is composed mainly of iron and nickel.' },
  { id: 12, term: 'Crust', translation: 'Земная кора', transcription: '/krʌst/', example: 'The oceanic crust is thinner than the continental crust.' },
  { id: 13, term: 'Delta', translation: 'Дельта', transcription: '/ˈdɛltə/', example: 'The river deposits sediment at its mouth, forming a large delta.' },
  { id: 14, term: 'Deposition', translation: 'Отложение', transcription: '/ˌdɛpəˈzɪʃən/', example: 'Deposition of sand created the dunes.' },
  { id: 15, term: 'Dike', translation: 'Дайка', transcription: '/daɪk/', example: 'A vertical dike of basalt cut through the older sandstone layers.' },
  { id: 16, term: 'Dolomite', translation: 'Доломит', transcription: '/ˈdɒləmaɪt/', example: 'Dolomite is a carbonate mineral and a rock.' },
  { id: 17, term: 'Drumlin', translation: 'Друмлин', transcription: '/ˈdrʌmlɪn/', example: 'The glacier left behind a field of elongated drumlins.' },
  { id: 18, term: 'Earthquake', translation: 'Землетрясение', transcription: '/ˈɜːrθkweɪk/', example: 'The earthquake was caused by movement along a fault line.' },
  { id: 19, term: 'Erosion', translation: 'Эрозия', transcription: '/ɪˈroʊʒən/', example: 'Wind and water are powerful agents of erosion.' },
  { id: 20, term: 'Esker', translation: 'Оз', transcription: '/ˈɛskər/', example: 'An esker is a long, winding ridge of sand and gravel.' },
  { id: 21, term: 'Fault', translation: 'Разлом', transcription: '/fɔːlt/', example: 'The San Andreas Fault is a major transform fault.' },
  { id: 22, term: 'Feldspar', translation: 'Полевой шпат', transcription: '/ˈfɛldspɑːr/', example: 'Feldspar is one of the most abundant minerals in the Earth\'s crust.' },
  { id: 23, term: 'Fjord', translation: 'Фьорд', transcription: '/fjɔːrd/', example: 'Norway is famous for its deep, scenic fjords.' },
  { id: 24, term: 'Fossil', translation: 'Окаменелость', transcription: '/ˈfɒsəl/', example: 'They discovered a dinosaur fossil in the sedimentary rock.' },
  { id: 25, term: 'Geode', translation: 'Жеода', transcription: '/ˈdʒiːoʊd/', example: 'When they broke the rock, they found a beautiful amethyst geode inside.' },
  { id: 26, term: 'Geyser', translation: 'Гейзер', transcription: '/ˈɡaɪzər/', example: 'Old Faithful is a famous geyser in Yellowstone National Park.' },
  { id: 27, term: 'Glacier', translation: 'Ледник', transcription: '/ˈɡleɪʃər/', example: 'The glacier carved out a U-shaped valley.' },
  { id: 28, term: 'Gneiss', translation: 'Гнейс', transcription: '/naɪs/', example: 'Gneiss is a high-grade metamorphic rock with distinct banding.' },
  { id: 29, term: 'Gondwana', translation: 'Гондвана', transcription: '/ɡɒndˈwɑːnə/', example: 'Gondwana was a supercontinent in the Southern Hemisphere.' },
  { id: 30, term: 'Granite', translation: 'Гранит', transcription: '/ˈɡrænɪt/', example: 'Granite is a coarse-grained intrusive igneous rock.' },
  { id: 31, term: 'Groundwater', translation: 'Подземные воды', transcription: '/ˈɡraʊndˌwɔːtər/', example: 'Many communities rely on groundwater for their drinking supply.' },
  { id: 32, term: 'Hotspot', translation: 'Горячая точка', transcription: '/ˈhɒtspɒt/', example: 'The Hawaiian Islands formed over a volcanic hotspot.' },
  { id: 33, term: 'Igneous rock', translation: 'Магматическая порода', transcription: '/ˈɪɡniəs rɒk/', example: 'Igneous rock is formed through the cooling and solidification of magma or lava.' },
  { id: 34, term: 'Intrusion', translation: 'Интрузия', transcription: '/ɪnˈtruːʒən/', example: 'The granite intrusion is younger than the surrounding rocks.' },
  { id: 35, term: 'Island arc', translation: 'Островная дуга', transcription: '/ˈaɪlənd ɑːrk/', example: 'Japan is an example of an island arc.' },
  { id: 36, term: 'Karst', translation: 'Карст', transcription: '/kɑːrst/', example: 'Karst topography is characterized by sinkholes and caves.' },
  { id: 37, term: 'Lava', translation: 'Лава', transcription: '/ˈlɑːvə/', example: 'Molten lava flowed from the volcano.' },
  { id: 38, term: 'Limestone', translation: 'Известняк', transcription: '/ˈlaɪmstoʊn/', example: 'Limestone is often rich in fossils.' },
  { id: 39, term: 'Lithosphere', translation: 'Литосфера', transcription: '/ˈlɪθəsfɪər/', example: 'The lithosphere is the rigid outer part of the earth.' },
  { id: 40, term: 'Loess', translation: 'Лёсс', transcription: '/ˈloʊəs/', example: 'Thick deposits of loess cover large areas of China.' },
  { id: 41, term: 'Magma', translation: 'Магма', transcription: '/ˈmæɡmə/', example: 'Magma is molten rock beneath the Earth\'s surface.' },
  { id: 42, term: 'Mantle', translation: 'Мантия', transcription: '/ˈmæntəl/', example: 'The mantle lies between the Earth\'s crust and core.' },
  { id: 43, term: 'Marble', translation: 'Мрамор', transcription: '/ˈmɑːrbəl/', example: 'Marble is a metamorphic rock formed from limestone.' },
  { id: 44, term: 'Metamorphic rock', translation: 'Метаморфическая порода', transcription: '/ˌmɛtəˈmɔːrfɪk rɒk/', example: 'Heat and pressure can change sedimentary rock into metamorphic rock.' },
  { id: 45, term: 'Mid-ocean ridge', translation: 'Срединно-океанический хребет', transcription: '/mɪdˈoʊʃən rɪdʒ/', example: 'New oceanic crust is formed at the mid-ocean ridge.' },
  { id: 46, term: 'Mineral', translation: 'Минерал', transcription: '/ˈmɪnərəl/', example: 'Quartz is a common mineral with a crystalline structure.' },
  { id: 47, term: 'Moraine', translation: 'Морена', transcription: '/məˈreɪn/', example: 'A terminal moraine marks the furthest advance of a glacier.' },
  { id: 48, term: 'Obsidian', translation: 'Обсидиан', transcription: '/əbˈsɪdiən/', example: 'Obsidian is a volcanic glass with sharp edges.' },
  { id: 49, term: 'Orogeny', translation: 'Орогенез', transcription: '/ɔːˈrɒdʒəni/', example: 'Orogeny refers to the process of mountain building.' },
  { id: 50, term: 'Outcrop', translation: 'Обнажение', transcription: '/ˈaʊtkrɒp/', example: 'Geologists studied the rock layers at the outcrop.' },
  { id: 51, term: 'Pangaea', translation: 'Пангея', transcription: '/pænˈdʒiːə/', example: 'Pangaea was a supercontinent that included almost all landmasses.' },
  { id: 52, term: 'Petrology', translation: 'Петрология', transcription: '/pɪˈtrɒlədʒi/', example: 'Petrology is the branch of geology that studies rocks.' },
  { id: 53, term: 'Plate tectonics', translation: 'Тектоника плит', transcription: '/pleɪt tɛkˈtɒnɪks/', example: 'The theory of plate tectonics explains the movement of the Earth\'s lithosphere.' },
  { id: 54, term: 'Porosity', translation: 'Пористость', transcription: '/pɔːˈrɒsɪti/', example: 'Sandstone has a high porosity, allowing it to hold water.' },
  { id: 55, term: 'Pumice', translation: 'Пемза', transcription: '/ˈpʌmɪs/', example: 'Pumice is a light, porous volcanic rock that can float on water.' },
  { id: 56, term: 'Pyroclastic flow', translation: 'Пирокластический поток', transcription: '/ˌpaɪroʊˈklæstɪk floʊ/', example: 'A pyroclastic flow is a fast-moving current of hot gas and volcanic matter.' },
  { id: 57, term: 'Quartz', translation: 'Кварц', transcription: '/kwɔːrts/', example: 'Quartz is one of the most common minerals on Earth.' },
  { id: 58, term: 'Quartzite', translation: 'Кварцит', transcription: '/ˈkwɔːrtsaɪt/', example: 'Quartzite is a hard, non-foliated metamorphic rock.' },
  { id: 59, term: 'Radioactive dating', translation: 'Радиометрическое датирование', transcription: '/ˌreɪdioʊˈæktɪv ˈdeɪtɪŋ/', example: 'Scientists used radioactive dating to determine the age of the fossil.' },
  { id: 60, term: 'Reef', translation: 'Риф', transcription: '/riːf/', example: 'Coral reefs are diverse underwater ecosystems.' },
  { id: 61, term: 'Richter scale', translation: 'Шкала Рихтера', transcription: '/ˈrɪktər skeɪl/', example: 'The earthquake measured 7.2 on the Richter scale.' },
  { id: 62, term: 'Rift valley', translation: 'Рифтовая долина', transcription: '/rɪft ˈvæli/', example: 'The East African Rift Valley is a classic example of a continental rift.' },
  { id: 63, term: 'Rock cycle', translation: 'Геологический цикл', transcription: '/rɒk ˈsaɪkəl/', example: 'The rock cycle describes the transformations between the three main rock types.' },
  { id: 64, term: 'Sandstone', translation: 'Песчаник', transcription: '/ˈsændstoʊn/', example: 'The cliffs were made of red sandstone.' },
  { id: 65, term: 'Schist', translation: 'Сланец', transcription: '/ʃɪst/', example: 'Schist is a metamorphic rock with a foliated texture.' },
  { id: 66, term: 'Sediment', translation: 'Осадок', transcription: '/ˈsɛdɪmənt/', example: 'The river carries a large amount of sediment.' },
  { id: 67, term: 'Sedimentary rock', translation: 'Осадочная порода', transcription: '/ˌsɛdɪˈmɛntəri rɒk/', example: 'Fossils are commonly found in sedimentary rock.' },
  { id: 68, term: 'Seismic wave', translation: 'Сейсмическая волна', transcription: '/ˈsaɪzmɪk weɪv/', example: 'Seismographs record the energy of seismic waves.' },
  { id: 69, term: 'Shale', translation: 'Сланец (глинистый)', transcription: '/ʃeɪl/', example: 'Shale is a fine-grained sedimentary rock that forms from mud.' },
  { id: 70, term: 'Shield volcano', translation: 'Щитовой вулкан', transcription: '/ʃiːld vɒlˈkeɪnoʊ/', example: 'Shield volcanoes have gentle slopes and are built of fluid lava flows.' },
  { id: 71, term: 'Sill', translation: 'Силл', transcription: '/sɪl/', example: 'A sill is a tabular sheet intrusion that has intruded between older layers.' },
  { id: 72, term: 'Sinkhole', translation: 'Карстовая воронка', transcription: '/ˈsɪŋkhoʊl/', example: 'A large sinkhole opened up in the middle of the road.' },
  { id: 73, term: 'Slate', translation: 'Сланец (кровельный)', transcription: '/sleɪt/', example: 'Slate is a fine-grained metamorphic rock used for roofing.' },
  { id: 74, term: 'Soil', translation: 'Почва', transcription: '/sɔɪl/', example: 'The soil in this region is very fertile for agriculture.' },
  { id: 75, term: 'Stalactite', translation: 'Сталактит', transcription: '/stəˈlæktaɪt/', example: 'Stalactites hang from the ceiling of a cave.' },
  { id: 76, term: 'Stalagmite', translation: 'Сталагмит', transcription: '/stəˈlæɡmaɪt/', example: 'Stalagmites grow up from the floor of a cave.' },
  { id: 77, term: 'Stratigraphy', translation: 'Стратиграфия', transcription: '/strəˈtɪɡrəfi/', example: 'Stratigraphy is the study of rock layers and layering.' },
  { id: 78, term: 'Stratum', translation: 'Слой (пласт)', transcription: '/ˈstrɑːtəm/', example: 'Each stratum represents a different period of deposition.' },
  { id: 79, term: 'Strike and dip', translation: 'Простирание и падение', transcription: '/straɪk ænd dɪp/', example: 'Geologists measure the strike and dip to understand the rock formation\'s orientation.' },
  { id: 80, term: 'Subduction', translation: 'Субдукция', transcription: '/səbˈdʌkʃən/', example: 'Subduction occurs when one tectonic plate moves under another.' },
  { id: 81, term: 'Syncline', translation: 'Синклиналь', transcription: '/ˈsɪŋklaɪn/', example: 'A syncline is a downward-folding rock structure.' },
  { id: 82, term: 'Tectonic', translation: 'Тектонический', transcription: '/tɛkˈtɒnɪk/', example: 'Earthquakes are a result of tectonic activity.' },
  { id: 83, term: 'Till', translation: 'Тиль (морена)', transcription: '/tɪl/', example: 'Till is unsorted sediment deposited directly by a glacier.' },
  { id: 84, term: 'Topography', translation: 'Топография', transcription: '/təˈpɒɡrəfi/', example: 'The topography of the area includes mountains and valleys.' },
  { id: 85, term: 'Transform fault', translation: 'Трансформный разлом', transcription: '/trænsˈfɔːrm fɔːlt/', example: 'A transform fault is a type of strike-slip fault.' },
  { id: 86, term: 'Trench', translation: 'Океанический жёлоб', transcription: '/trɛntʃ/', example: 'The Mariana Trench is the deepest oceanic trench on Earth.' },
  { id: 87, term: 'Tsunami', translation: 'Цунами', transcription: '/tsuːˈnɑːmi/', example: 'The undersea earthquake triggered a devastating tsunami.' },
  { id: 88, term: 'Tuff', translation: 'Туф', transcription: '/tʌf/', example: 'Tuff is a rock made of consolidated volcanic ash.' },
  { id: 89, term: 'Unconformity', translation: 'Несогласие (геол.)', transcription: '/ˌʌnkənˈfɔːrmɪti/', example: 'An unconformity represents a gap in the geologic record.' },
  { id: 90, term: 'Vein', translation: 'Жила', transcription: '/veɪn/', example: 'They found a vein of gold in the quartz rock.' },
  { id: 91, term: 'Volcano', translation: 'Вулкан', transcription: '/vɒlˈkeɪnoʊ/', example: 'Mount Fuji is a famous volcano in Japan.' },
  { id: 92, term: 'Water table', translation: 'Уровень грунтовых вод', transcription: '/ˈwɔːtər ˈteɪbəl/', example: 'During the drought, the water table dropped significantly.' },
  { id: 93, term: 'Weathering', translation: 'Выветривание', transcription: '/ˈwɛðərɪŋ/', example: 'Weathering is the breakdown of rocks at the Earth\'s surface.' },
  { id: 94, term: 'Facies', translation: 'Фация', transcription: '/ˈfeɪʃiːz/', example: 'Different sedimentary facies indicate different depositional environments.' },
  { id: 95, term: 'Paleontology', translation: 'Палеонтология', transcription: '/ˌpeɪliɒnˈtɒlədʒi/', example: 'Paleontology is the study of ancient life through fossils.' },
  { id: 96, term: 'Permeability', translation: 'Проницаемость', transcription: '/ˌpɜːrmiəˈbɪlɪti/', example: 'The permeability of the rock determines how easily water can flow through it.' },
  { id: 97, term: 'Anticline', translation: 'Антиклиналь', transcription: '/ˈæntɪklaɪn/', example: 'An anticline is an upward-arching fold in rock layers.' },
  { id: 98, term: 'Batholith', translation: 'Батолит', transcription: '/ˈbæθəlɪθ/', example: 'A batholith is a large mass of intrusive igneous rock.' },
  { id: 99, term: 'Extrusion', translation: 'Экструзия', transcription: '/ɪkˈstruːʒən/', example: 'Lava flows are a form of volcanic extrusion.' },
  { id: 100, term: 'Isostasy', translation: 'Изостазия', transcription: '/aɪˈsɒstəsi/', example: 'Isostasy explains how the Earth\'s crust floats on the mantle.' }
];

export const readingTexts: ReadingText[] = [
  {
    id: 1,
    title: 'Field Trip Discussion',
    type: 'Dialogue',
    content: `Alex: "Look at this outcrop! The layers of sandstone and shale are so clear."
Maria: "I think I see a fossil in this stratum. The history of deposition is written right here."
Alex: "Indeed. You can also see how erosion has shaped this cliff. This whole area is a classic example of sedimentary rock formation."`
  },
  {
    id: 2,
    title: 'Tectonic Activity',
    type: 'Scientific Article',
    content: `The theory of plate tectonics explains the movement of the lithosphere. At a mid-ocean ridge, magma rises from the mantle to form new oceanic crust, primarily composed of basalt. This process creates features like a rift valley. In contrast, at subduction zones, older crust is recycled back into the mantle, driving the entire dynamic system.`
  },
  {
    id: 3,
    title: 'Volcanic Zone Observations',
    type: 'Journal Entry',
    content: `Today we explored the remnants of an ancient volcano. The ground is littered with pumice and sharp obsidian. Our guide warned us about the dangers of a potential pyroclastic flow in active areas. The massive caldera is breathtaking. Nearby, a geyser erupts on schedule, a clear sign of the hotspot activity below. We even saw cooled lava flows from centuries ago.`
  },
  {
    id: 4,
    title: 'Identifying Rocks',
    type: 'Dialogue',
    content: `Teacher: "What type of rock is this?"
Student: "It's an igneous rock, specifically granite, because I can see large crystals."
Teacher: "Correct! And this one?"
Student: "It's a metamorphic rock. Maybe marble or gneiss?"
Teacher: "Look at the banding. It's gneiss. Each band has a different mineral. Notice the cleavage on this piece of quartz."`
  },
  {
    id: 5,
    title: 'Glacial Landforms',
    type: 'Scientific Article',
    content: `A retreating glacier leaves behind distinct landforms. A terminal moraine, composed of unsorted till, marks its furthest advance. Elongated hills called drumlin fields and winding ridges known as esker formations are also common. The process of glacial abrasion carves the underlying bedrock, while post-glacial weathering continues to shape the landscape.`
  },
];
